version: "3"

services:
  mysql2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111 
      MYSQL_DATABASE: drupal 
      MYSQL_USER: user 
      MYSQL_PASSWORD: 1111 
  drupal2:
    image: custom-drupal:latest
    volumes:
      - ./drupal-data:/var/lib/postgresql/data
    ports:
      - 8090:80

 
