version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111 
      MYSQL_DATABASE: drupal 
      MYSQL_USER: user 
      MYSQL_PASSWORD: 1111 
  drupal:
    image: drupal:latest
    ports:
      - 8080:80

 
