version: "3"
services:
  voting-app:
      image: bretfisher/examplevotingapp_vote
      deploy:
        placement:
          constraints: [node.role != manager]
      ports:
        - 80:80
      networks:
        - frontend

  redis:
      image: redis:3.2
      deploy:
        placement:
          constraints: [node.role != manager]
      networks:
        - frontend

  worker:
      image: bretfisher/examplevotingapp_worker:java
      deploy:
        placement:
          constraints: [node.role != manager]
      networks:
        - frontend
        - backend

  db:
      image: postgres:9.4
      deploy:
        placement:
          constraints: [node.role != manager]
      volumes: 
        - db-data:/var/lib/postgresql/data
      networks:
        - frontend

  result-app:
      image: bretfisher/examplevotingapp_result
      deploy:
        placement:
          constraints: [node.role != manager]
      depends_on:
        - db
      ports:
        - 81:80 
      networks:
        - backend

volumes:
  db-data:
  

networks:
  frontend:
    external: true

  backend:
    external: true


